[package]
name = "bool-toggle"
description = "bool toggling for the bool toggle enjoyers"
version = "1.0.0"
edition = "2021"
license = "MIT"

[package.metadata.docs.rs]
# enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]
